AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Template that creates DNS Records

Parameters:
  domain:
    Type: String
    Description: Domain
  
  domainHostedZone:
    Type: String
    Description: Domain Hosted Zone

  albDomain:
    Type: String
    Description: Load Balancer dns domain
  
  albHostedZone:
    Type: String
    Description: Load Balancer Hosted Zone
  
  wwwCloudfrontDomain:
    Type: String
    Description: Cloudfront Domain

Resources:
  DomainRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Ref domain
      HostedZoneId: !Ref domainHostedZone
      Type: A
      AliasTarget:
        HostedZoneId: !Ref albHostedZone
        DNSName: !Ref albDomain

  WWWRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Sub 'www.${domain}'
      HostedZoneId: !Ref domainHostedZone
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !Ref wwwCloudfrontDomain