Parameters:
  domain:
    Type: String
    Description: Registrated Domain  
  
  wwwBucket:
    Type: String 
    Description: WWW Bucket Name
  
  enableHTTPS:
    Type: String
    Description: Flag to enable HTTPS connection
    Default: false

  cfCertificateARN:
    Type: String
    Description: Cloudfront Certificate ARN
    Default: ''

Conditions:
  EnableHTTPS: !Equals ['true', !Ref enableHTTPS]

Resources:
  WWWCloudfront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: Cloudfront distribution for WWW Domain
        Aliases: 
          - !If [ EnableHTTPS, !Sub 'www.${domain}', !Ref 'AWS::NoValue' ] 
        Origins:
          - Id: WWWOrigin
            DomainName: !Sub '${wwwBucket}.s3-website.${AWS::Region}.amazonaws.com'
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
        Enabled: true
        HttpVersion: 'http2'
        PriceClass: PriceClass_All
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - HEAD
          - OPTIONS
          Compress: true
          TargetOriginId: WWWOrigin
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          ViewerProtocolPolicy: allow-all
        ViewerCertificate:
          !If 
            - EnableHTTPS
            - AcmCertificateArn: !Ref cfCertificateARN
              SslSupportMethod: sni-only
              MinimumProtocolVersion: TLSv1.1_2016
            - !Ref 'AWS::NoValue'
          

Outputs:
  CloudfrontDomain:
    Value: !GetAtt WWWCloudfront.DomainName