AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Template that creates and configure an S3 Bucket to redirect the WWW domain to the Apex domain

Parameters:
  domain:
    Type: String
    Description: Domain
  
Resources:
  WWWBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'www.${domain}'
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Ref domain
          Protocol: https
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  
Outputs:
  WWWBucketName:
    Description: WWW Bucket Name
    Value: !Ref WWWBucket